version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data
    networks:
      - paybook_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "paybook"]
    restart: always
    networks:
      - paybook_network

volumes:
  postgres:
  redis_data:


networks:
  paybook_network:
    driver: bridge
