@env = dev

### Get months json
GET http://localhost:8080/api/transactions/months
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get full balance
GET http://localhost:8080/api/transactions/balance?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get income balance
GET http://localhost:8080/api/transactions/income/balance?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get expense balance
GET http://localhost:8080/api/transactions/expense/balance?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get debt balance
GET http://localhost:8080/api/transactions/debt/balance?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}



### Get income transactions
GET http://localhost:8080/api/transactions/income?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get income transactions
GET http://localhost:8080/api/transactions/expense?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Get debt transactions
GET http://localhost:8080/api/transactions/debt?month=2025.06.01
Content-Type: application/json
Authorization: Bearer {{accessToken}}